### ISSUE TITLE
blue smart chargers

### ISSUE THREAD

**Issue by aktxyz** [Fabian-Schmidt/esphome-victron_ble#52] opened 2024-05-29 05:11 UTC
It sounds like the docs are not complete for supporting these blue smart chargers?

https://www.victronenergy.com/chargers/blue-smart-ip22-charger

**Comment by Fabian-Schmidt** [comment] 2024-06-01 08:13
It looks like the blue smart charger does not support the instant readout feature.

<https://www.victronenergy.com/media/pg/VictronConnect_Manual/en/stored-trends---instant-readout.html#UUID-5eec18d4-9e11-0845-47e5-9a8f0cec49f4>

This component is using the instant readout feature. If the victron device does not support it than there is nothing I can do.

**Comment by Fabian-Schmidt** [comment] 2024-06-01 08:28
Add to readme aabd1d37041dcea64039961995e3e6e7fa51658c

**Comment by n4rrOx** [comment] 2024-10-18 12:30
Hello Fabian, 
it looks like Victron has answered our prayers ;-)

source:	[https://www.victronenergy.com/live/victronconnect:beta#v610beta14](url)
> 	Changelog v6.10beta14 from 2024-09-28
Applies to all IP22, IP65 and IP67 Blue Smart Chargers 
 => Firmware v3.61 change log: Add Instant Readout

@Donixon already contributed some more ble readout dumps here:
[https://github.com/keshavdv/victron-ble/issues/60](url)

So...is it possible to add these devices to your project?

**Comment by HBK1** [comment] 2024-10-18 12:33
https://github.com/Fabian-Schmidt/esphome-victron_ble/issues/62#issuecomment-2416393433

**Comment by Fabian-Schmidt** [comment] 2024-10-20 10:40
I close this as a duplicate of #62 .

**Closed by Fabian-Schmidt** 2024-10-20 10:40 UTC
